### ISSUE TITLE
Bug: after winning text mode, the reported solution does not work

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#148]
This is a reported solution for hard 1
```
:solution.1=8;bridge;1;1;(12,7);1;(12,7);1;1;1;1;1;1;1;(10,6);1;1;1;1;1;1;(13,4);1;1;1;1;4;2;2;2;2;1;1;1;1;1;1;1;1;
```
(plus/minus a bit of waiting). I put some println in world.step() to see what happened.
```
    [junit] RUNNING saved0 killed0
    [junit] RUNNING saved0 killed0
   <snip>
    [junit] RUNNING saved0 killed0
    [junit] RUNNING saved0 killed0
    [junit] RUNNING saved0 killed1
    [junit] RUNNING saved0 killed1
    [junit] RUNNING saved0 killed2
    [junit] RUNNING saved0 killed2
    [junit] RUNNING saved0 killed3
    [junit] RUNNING saved0 killed3
```
They are dying in there!  but I can't see how.

**Comment by colonelfazackerley** [comment]
Kludging this into the end of World.step temporarily gives a clue
```
        System.out.println(""+completionState()+ " saved"+num_saved+" killed"+num_killed);
        String[] w=TextWorldManip.renderWorld( this, false, false );
        for (String s: w) System.out.println(s);
```

There is a spurious extra timestep inserted in recording or playback. After deleting this, the test works for hard 1.

**Comment by colonelfazackerley** [comment]
I am having a similar problem with hard 2. The timing is off. It is not as simple as inserting an extra '1;' at the start. I have not figured it out yet.

**Comment by colonelfazackerley** [comment]
Further "instrumenting" of World has enabled me to make a solution to hard 2.
```diff
--- a/rabbit-escape-engine/src/rabbitescape/engine/World.java
+++ b/rabbit-escape-engine/src/rabbitescape/engine/World.java
@@ -7,6 +7,7 @@ import java.util.List;
 import java.util.Map;
 
 import rabbitescape.engine.err.RabbitEscapeException;
+import rabbitescape.engine.textworld.TextWorldManip;
 import rabbitescape.engine.util.Dimension;
 
 public class World
@@ -115,6 +116,7 @@ public class World
     public int num_saved;
     public int num_killed;
     public int num_waiting;
+    public int step_count = 0;
 
     public boolean paused;
 
@@ -203,6 +205,10 @@ public class World
         }
 
         changes.apply();
+
+        System.out.println("\n"+(++step_count)+" "+completionState()+ " saved"+num_saved+" killed"+num_killed);
+        String[] w=TextWorldManip.renderWorld( this, false, true );
+        for (String s: w) System.out.println(s);
     }
 
     public ChangeDescription describeChanges()

```

I am a little concerned that if the bug is in running the solution, then my effort is wasted.

**Comment by tttppp** [comment]
My solution to hard 1 worked fine in the All_solutions_are_correct test. Initially it printed the message you got though.

The incorrect id of 0 is due to this line: https://github.com/andybalaam/rabbit-escape/commit/281466b9f03d87c64fa0045466dceaf441dd5930#commitcomment-14175813

However, Andy also changed the data structure to be an array of solutions, rather than a map, so the ids don't actually do anything at the moment as far as I can see.

To get the given solution to run I had to replace ";;" with ";1;" (twice using eclipse), but then it succeeded. The solution simplification work I started should fix this, and also make the long lists of "1;1;1;1;1;1" much easier to read.

**Comment by tttppp** [comment]
Another way of looking at the solution id issue is that you should change
```
:solution.1=8;bridge...
```
to
```
:solution.0=8;bridge...
```
and everything will work as expected.

**Comment by colonelfazackerley** [comment]
The hints count from 1. I would find it more pleasing if the hints and solutions both counted the same.

I can imaging a level where there was 
solution.0
solution.1
solution.2
and solution.1 was removed. The counting would be confusing again. 

Could instances of solution not keep a record of the number they were assigned in the .rel file? (I have not looked at the code).

**Comment by tttppp** [comment]
Yes, I think this would be better to allow arbitrary solution ids (possibly integer only?) and store these in the solutions. The code used to store a map of ids and solutions in the LineProcessor. Andy moved this to the World (which is a much more sensible place), but he lost the map structure in the process.

You're right to identify hints as a similar case, and we should change to become consistent one way or the other. (Personally I'd prefer positive integer ids, and when iterating through them skip any missing ids. I would allow 0 as an id,  but not enforce that it is present).

**Comment by andybalaam** [comment]
Again, I haven't looked but it sounds like I introduced a bug when I changed it to an array, because arrays are zero-based and I am not adjusting properly for that.  Sorry if so, and I will try to fix (but feel free to get there first).

I don't see any need for arbitrary IDs, but the code as I intended it replaced any missing solution with "", which of course fails, so maybe isn't a good idea.

**Comment by andybalaam** [comment]
(When I say "missing solution" I mean if it encounters solutions numbers with gaps in between it fills in the gaps with empty solutions.)

All levels that are in production should surely have N solutions numbered 1..N, right?  If you can convince me otherwise I will be persuaded to go back to a map of ID->solution.

**Comment by colonelfazackerley** [comment]
I think it's fine to make things like
:solution.0=blah
:solution.2=blah
illegal, as long as a clear error message is given when the world is constructed.

**Comment by andybalaam** [comment]
78629ff076c8e813b244fb07ed7f2b403faac1f3 fixes some of my unforgiveable errors.  Hopefully enough that it works for you now?

**Comment by andybalaam** [comment]
We may need further fixes to make e.g. `solution.0` illegal without causing a crash.  Out of time now but will take a look if no-one else does first.

**Comment by colonelfazackerley** [comment]
I did hard 3 in text mode. I made sure to always enter 1, not just hit return.I manually tidied to this
```
:solution.1=bash;(4,10);(7,4);(4,5);bridge;6;(9,10);8;climb;(7,8);(7,8);11
```
but it needs more steps at the end. using my "instrumented" world, I find it should be 
```
:solution.1=bash;(4,10);(7,4);(4,5);bridge;6;(9,10);8;climb;(7,8);(7,8);18;WON
```

**Comment by colonelfazackerley** [comment]
Hang on. I had to add 7 timesteps. Instructions where I dropped tokens are 6 in total
1 bash
2 (4,10)
3 (7,4)
4 (4,5) 
5 bridge
6 (9,10)
7 climb
8 (7,8)
9 (7,8)

so, is the solution player stepping 1 when a token is dropped? (plus one more obi-one)

**Comment by tttppp** [comment]
I'm happy with the array solutions being continuous and starting at 1.

I'm really intrigued by the 11 steps/18 steps bug step. Maybe we should do some solutions to easier levels first to iron out the bugs? Weird stuff anyway.

**Comment by colonelfazackerley** [comment]
easy levels probably wont require critical timing for token drops. may not see the bugs.

level hard 4
(last thing I typed was 3, so I don't know why there is a '1' on the end).
```
:solution.1=block;(7,3);7;bridge;(9,13);10;(12,5);6;6;4;4;2;(9,3);dig;(12,10);10;10;10;10;8;explode;(7,2);3;1
:solution.1.code=twGE7q,,,,O4IE!E,(GEH\t,!Kw,8=E"E!E,,,qEEEEHtH-KeK7}\!I()k!KhtEEEKtqE-q=!Eqwl"K7EEqG-}EEw7eEE3tE)
You won!
```

manual tidy
```
:solution.1=block;(7,3);7;bridge;(9,13);10;(12,5);22;(9,3);dig;(12,10);48;explode;(7,2);4;WON
```

didn't work. extra '1' after each token drop
```
:solution.1=block;(7,3);1;7;bridge;(9,13);1;10;(12,5);1;22;(9,3);1;dig;(12,10);1;48;explode;(7,2);1;4;WON
```

didn't work. move extra '1' before each token drop
```
:solution.1=block;1;(7,3);7;bridge;1;(9,13);10;1;(12,5);22;1;(9,3);dig;1;(12,10);48;explode;1;(7,2);4;WON
```

closer examination of the extra output i put into World shows the last bridge is dropped around 6 steps too early. maybe other things different to how i played it, but that is a time critical token placement. try
```
:solution.1=block;1;(7,3);7;bridge;1;(9,13);10;1;(12,5);22;1;6;(9,3);dig;1;(12,10);48;explode;1;(7,2);4;WON
```

delay the euthanasia
```
:solution.1=block;1;(7,3);7;bridge;1;(9,13);10;1;(12,5);22;1;6;(9,3);dig;1;(12,10);48;explode;1;6;(7,2);4;WON
```

even more. this is probably becuase of a subtle timing change earlier on. having to wait for a rabbit to walk back and forth more.
```
:solution.1=block;1;(7,3);7;bridge;1;(9,13);10;1;(12,5);22;1;6;(9,3);dig;1;(12,10);48;explode;1;6;14;(7,2);4;WON
```

this works, but now i get World.DontStepAfterFinish. reduce padding at the end. this works.
```
:solution.1=block;1;(7,3);7;bridge;1;(9,13);10;1;(12,5);22;1;6;(9,3);dig;1;(12,10);48;explode;1;6;14;(7,2);2;WON
```

tidy
```
:solution.1=block;(7,3);bridge;9;(9,13);(12,5);40;(9,3);dig;1;(12,10);explode;69;(7,2);2;WON
```

simplify more
```
:solution.1=block;(7,3);bridge;9;(9,13);(12,5);41;(9,3);dig;(12,10);explode;69;(7,2);2;WON
```

so, missing a time step for each token drop is not the answer. I am definitely having to insert time steps into the text mode win report, though.

**Comment by andybalaam** [comment]
I think the heart of this must be the lack of a 1-1 correspondence between the text and the Instructions list.I think the transformations we apply should be done separately from the parsing.

**Comment by andybalaam** [comment]
I am going to continue my planned further refactoring of solutions.  @tttppp sorry if this tramples on something you are doing.  I plan to make a SolutionRunner an Iterable<SolutionTimeStep>, and a Solution an exact parse of the solution string.  Hopefully when you see the code it will make sense.  Feel free to ping me if you are working tonight,

**Comment by colonelfazackerley** [comment]
I tested my algorithm for fixing the text mode solution report.
- avoid just hitting enter when playing. always give a wait time.
- change the '1' it adds to the end to 'WON'
- add 1 to each wait time instruction.

fixing this should fix #161 too.

**Comment by colonelfazackerley** [comment]
update

-    change the '1' it adds to the end to 'WON'
-   add 1 to each wait time instruction that has a number
- If you just hit enter, so you have semicolons without gaps between in the reported solution. insert '1'

**Comment by tttppp** [comment]
Thanks for you pointer @colonelfazackerley. It was easy to track down the extra wait steps being performed in the TextGameLaunch. I think this is now fixed on my recordingSimplifier branch.

**Comment by colonelfazackerley** [comment]
This bug is back.'make test' is OK with hard set solutions, so I think the bug is in text mode reporting.

**Comment by andybalaam** [comment]
See my @Ignored unit tests for converting to text for some possible clues.

**Comment by colonelfazackerley** [comment]
```
#!/usr/bin/expect
# sudo apt-get install expect

set timeout 20

spawn java -cp rabbit-escape-engine/bin/:rabbit-escape-render/bin/:rabbit-escape-ui-text/bin/:rabbit-escape-ui-swing/bin/ rabbitescape.ui.text.TextMain

# Start Game
send "1\r"

# Hard
send "3\r"

# Level 1
send "1\r"

# play
# :solution.2=bridge;(11,7);11;(12,7);2;(12,7);4;(12,7);2;(10,6);16;(13,4);5;(13,4);14

expect ">" 
send "bridge\r"
send "(11,7)\r"
send "11\r"
send "(12,7)\r"
send "2\r"
send "(12,7)\r"
send "4\r"
send "(12,7)\r"
send "2\r"
send "(10,6)\r"
send "16\r"
send "(13,4)\r"
send "5\r"
send "(13,4)\r"
send "14\r"


interact
```
it then gives
:solution.1=bridge&(11,7);10;(12,7);1;(12,7);3;(12,7);1;(10,6);15;(13,4);4;(13,4);13;

it's losing a step from each wait in the report

**Comment by andybalaam** [comment]
Kudos for figuring out expect. I got really confused then had to do some stupid task like go to work.
